### ISSUE TITLE
Formulate better plan for leading/trailing and insets

### ISSUE THREAD

**Issue by banDedo** [Masonry/Snap#60]
This snippet:
        loginButton.snp_makeConstraints { make in
            make.left.and.right.equalTo(UIEdgeInsetsMake(0.0, 10.0, 0.0, 10.0))
            make.height.equalTo(100.0)
            make.centerY.equalTo(0.0)
        }
produces different results then this one:
        loginButton.snp_makeConstraints { make in
            make.leading.and.trailing.equalTo(UIEdgeInsetsMake(0.0, 10.0, 0.0, 10.0))
            make.height.equalTo(100.0)
            make.centerY.equalTo(0.0)
        }

The latter does not inset the button at all.  Any ideas?

**Comment by robertjpayne** [comment]
Is there any API to lookup reading directions? Leading/Trailing are to be used to interfaces are left to right or right to left depending on the users language ( Arabic trailing is left etc… ).

Maybe, however, we always use left/right for leading/trailing?

**Comment by banDedo** [comment]
@robertjpayne I typically like to use leading and trailing because the lend themselves to an internationalized treatment of layout.  In this case I don't see why there are no insets.  Any ideas why this would be the case?

**Comment by robertjpayne** [comment]
@banDedo so the issue really is that you're using leading/trailing for the specific reason I have not allowed insets to be applied to them:

For instance:

`make.leading.trailing.equalTo(otherView).insets(UIEdgeInsets(top: 0, left: 50, bottom: 0, right: 0))`

Am I supposed to apply left to leading or to trailing? In English it would be leading but in Arabic it would be trailing.

Again it's mostly a terminology thing but left != leading and that is the current reason insets are not allowed on leading/trailing.

**Comment by banDedo** [comment]
@robertjpayne This is a great reason.  Thanks for the explanation.

**Comment by robertjpayne** [comment]
@banDedo what I may allow is for the insets function to take a "CGFloat" and if it's a CGFloat it will apply that properly all around thus you could do:

make.leading.trailing.equalTo(otherView).insets(5) which would mean you want 5 on each side. Because it's not an issue if it's identical on each side.

**Comment by banDedo** [comment]
@robertjpayne I think this is one solution.  Another would be to typedef an insets struct that has leading, trailing, top, and bottom fields.

**Comment by robertjpayne** [comment]
@banDedo true, but the initialiser for such a struct would be messy.

**Comment by banDedo** [comment]
I figured as much.  Thanks for the awesome package.  I have been using Masonry/Snap for over a year.  It's by far my favorite third party framework.

**Comment by robertjpayne** [comment]
@banDedo so I wanted to do this via looking up the read direction at runtime via `UIApplication.sharedApplication(). userInterfaceLayoutDirection`. Unfortunately Swift complains and says I cannot use it because Snap is a framework.

Instead I've added a `Snap.Config.interfaceLayoutDirection` variable which defaults to `.LeftToRight`. You can at runtime configure this before setting up any constraints and this should ensure leading/trailing offsets/constants are handled properly now.

Please note this is only available on `develop` right now.

**Comment by robertjpayne** [comment]
Going to close this as it's on the develop branch and into the milestone!

**Comment by banDedo** [comment]
Perfect solution. Thanks for the follow up.

**Comment by robertjpayne** [comment]
@banDedo this may change a bit in the next release. Playing around with the rest of UIKit that takes UIEdgeInsets basically it ensures whatever you set is matched onscreen.

So a scroll view with a right edge inset of 30 will always show a right edge inset of 30 regardless of language direction.

I'm updating the logic in Snap to double down on this. If you pass in UIEdgeInsets to make.leading.trailing.top.bottom it will always ensure that the edge insets are matched on screen.
