### ISSUE TITLE
iOS 7.0 & Cocoapods

### ISSUE THREAD

**Issue by Cedrick84** [Masonry/Snap#79]
Hi,

Your readme says it is compatible with 7.0 but your podspec says 8. Could you please update one of the two. Cheers!

**Comment by robertjpayne** [comment]
@Cedrick84 unfortunately Cocoapods only supports iOS 8.0 for Swift integration because of the need for dynamic frameworks and the fact they are not accepted into the app store for iOS 7.0 targets.

Your best integration option is to manually include the *.swift files into your application target.

Hope this helps.
